name: Setup Insiders
description: Setup the Insiders repo in a path
inputs:
  path:
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: Install Node
      uses: actions/setup-node@v3

    - name: Yarn
      run: yarn
      working-directory: ${{ inputs.path }}
      shell: bash
