name: Publish

on:
  push:
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Insiders
        uses: actions/checkout@v3
        with:
          path: insiders

      - name: Setup Insiders
        run: yarn
        working-directory: insiders

      - name: Checkout Zui
        uses: actions/checkout@v3
        with: 
          repository: brimdata/brim
          ref: welcome-zui # This will change to main
          path: zui
      
      - name: Save Most Recently Built Version
        run: yarn bump ../zui
        working-directory: insiders

      - name: Commit Changes
        working-directory: insiders
        run: |
          git diff
          git config --global user.name 'Zui Insiders Automation'
          git config --global user.email 'support@brimdata.io'
          git commit -am "automation: Bump version for successful release"
          git push
