name: Publish

on:
  push:
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Insiders
        uses: actions/checkout@v3
        with:
          path: insiders

      - name: Checkout Zui
        uses: actions/checkout@v3
        with: 
          repository: brimdata/brim
          ref: welcome-zui # This will change to main
          path: zui
      
      - name: Save Most Recently Built Version
        run: node insiders/index.js zui
