name: Publish

on:
  push:
  workflow_dispatch:

jobs:
  release:
    strategy:
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Insiders
        uses: actions/checkout@v3
        with:
          path: insiders
      
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: insiders/yarn.lock

      - name: Yarn
        run: yarn
        working-directory: insiders

      - name: Checkout Zui
        uses: actions/checkout@v3
        with:
          repository: brimdata/brim
          ref: welcome-zui # Change to main later
      
      - name: Inject package.json
        run: yarn inject ../
        working-directory: insiders

      - name: Remove insiders
        run: rm -fr insiders

      - name: Setup Zui
        uses: ./.github/actions/setup-zui

      - name: Build Zui
        uses: ./.github/actions/build-zui
        with:
          cmd: yarn electron-builder -c electron-builder-insiders.json
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          # Windows
          csc_key_password: ${{ secrets.WINDOWS_SIGNING_PASSPHRASE }}
          csc_link: ${{ secrets.WINDOWS_SIGNING_PFX_BASE64 }}
          # Mac
          apple_id: ${{ secrets.APPLEID_USER }}
          apple_id_password: ${{ secrets.APPLEID_PASSWORD }}
          cert_p12: ${{ secrets.APPLE_DEVELOPER_ID_CERT_P12_BASE64 }}
          cert_passphrase: ${{ secrets.APPLE_DEVELOPER_ID_CERT_PASSPHRASE }}

  bump:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Insiders
        uses: actions/checkout@v3
        with:
          path: insiders
      
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          cache: yarn

      - name: Yarn
        run: yarn
        working-directory: insiders

      - name: Checkout Zui
        uses: actions/checkout@v3
        with: 
          repository: brimdata/brim
          ref: welcome-zui # This will change to main
          path: zui
      
      - name: Save Most Recently Built Version
        run: yarn bump ../zui
        working-directory: insiders

      - name: Commit Changes
        working-directory: insiders
        run: |
          git diff
          git config --global user.name 'Zui Insiders Automation'
          git config --global user.email 'support@brimdata.io'
          git commit -am "automation: Bump version for successful release"
          git push
