name: Create New Release

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '5 15 * * 1-5' # Every weekday at 5:15am

jobs:
  next-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-latest.output.version}}

    steps:
      - name: Checkout Insiders
        uses: actions/checkout@v3
        with:
          path: insiders
      
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: insiders/yarn.lock

      - name: Yarn
        run: yarn
        working-directory: insiders

      - name: Test Latest version
        run: yarn latest

      - name: Get latest Zui Insiders release version
        id: get-latest
        run: echo "::set-output name=version::$(yarn latest)"
        working-directory: insiders

  # release:
  #   needs: next-version
  #   strategy:
  #     matrix:
  #       platform: [windows-latest, macos-latest, ubuntu-latest]

  #   runs-on: ${{ matrix.platform }}
  #   steps:
  #     - name: Checkout Zui
  #       uses: actions/checkout@v3
  #       with:
  #         repository: brimdata/brim
  #         ref: welcome-zui # Change to main later

  #     - name: Checkout Insiders
  #       uses: actions/checkout@v3
  #       with:
  #         path: insiders
      
  #     - name: Install Node
  #       uses: actions/setup-node@v2
  #       with:
  #         cache: yarn
  #         cache-dependency-path: insiders/yarn.lock

  #     - name: Yarn
  #       run: yarn
  #       working-directory: insiders

  #     - name: Inject package.json
  #       run: yarn inject ../
  #       working-directory: insiders
  #       env:
  #         LATEST_INSIDERS_VERSION: ${{ needs.next-version.outputs.version }}

  #     - name: Remove insiders
  #       run: rm -fr insiders
  #       shell: bash

  #     - name: Disable yarn immutable installs
  #       run: yarn config set enableImmutableInstalls false

  #     - name: Setup Zui
  #       uses: ./.github/actions/setup-zui

  #     - name: Build Zui
  #       uses: ./.github/actions/build-zui
  #       with:
  #         cmd: yarn electron-builder -c electron-builder-insiders.json --publish always
  #         gh_token: ${{ secrets.GITHUB_TOKEN }}
  #         # Windows
  #         csc_key_password: ${{ secrets.WINDOWS_SIGNING_PASSPHRASE }}
  #         csc_link: ${{ secrets.WINDOWS_SIGNING_PFX_BASE64 }}
  #         # Mac
  #         apple_id: ${{ secrets.APPLEID_USER }}
  #         apple_id_password: ${{ secrets.APPLEID_PASSWORD }}
  #         cert_p12: ${{ secrets.APPLE_DEVELOPER_ID_CERT_P12_BASE64 }}
  #         cert_passphrase: ${{ secrets.APPLE_DEVELOPER_ID_CERT_PASSPHRASE }}
